import React from 'react'


export const metadata = {
    title: "team page",
    // description: "Generated by create next app",
  };


const TeamPage = () => {
  return (
    <div>
      TeamPage
    </div>
  )
}

export default TeamPage
